### PR TITLE
son-profile implementation

### PR DESCRIPTION
**Pull request by mpeuster**
Much more implementation of son-profile. 

Working:

- read PED file
- extract input service package
- generate experiments according to parameter studies#
- generate service project for each experiment to be executed

... still lots of work TBD.

### CODE REVIEW

**Comment by mpeuster** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Pull request merged**
